// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSSFinalProject12_27.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NSSFinalProject12_27.Migrations
{
    [DbContext(typeof(NSSFinalProjectDbContext))]
    [Migration("20250115211906_AddCreatorUserIdToRepository")]
    partial class AddCreatorUserIdToRepository
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnotationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnotationId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Annotations");

                    b.HasData(
                        new
                        {
                            AnnotationId = 1,
                            Content = "This backend framework looks promising for my next project.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(4640),
                            RepositoryId = 1,
                            Type = "Note",
                            UserId = "1"
                        },
                        new
                        {
                            AnnotationId = 2,
                            Content = "Great library for frontend animations.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(4650),
                            RepositoryId = 2,
                            Type = "Note",
                            UserId = "2"
                        },
                        new
                        {
                            AnnotationId = 3,
                            Content = "AI",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(4650),
                            RepositoryId = 3,
                            Type = "Tag",
                            UserId = "3"
                        },
                        new
                        {
                            AnnotationId = 4,
                            Content = "Data science repo with useful algorithms.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(4650),
                            RepositoryId = 4,
                            Type = "Note",
                            UserId = "4"
                        },
                        new
                        {
                            AnnotationId = 6,
                            Content = "Automated Testing",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5180),
                            RepositoryId = 9,
                            Type = "Tag",
                            UserId = "7"
                        },
                        new
                        {
                            AnnotationId = 7,
                            Content = "Great sandbox for testing ML algorithms.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5180),
                            RepositoryId = 10,
                            Type = "Note",
                            UserId = "8"
                        },
                        new
                        {
                            AnnotationId = 8,
                            Content = "Full Stack",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5180),
                            RepositoryId = 11,
                            Type = "Tag",
                            UserId = "9"
                        },
                        new
                        {
                            AnnotationId = 9,
                            Content = "Awesome data visualization library for presentations.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5180),
                            RepositoryId = 12,
                            Type = "Note",
                            UserId = "10"
                        },
                        new
                        {
                            AnnotationId = 10,
                            Content = "Could use this for testing in our current project.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5190),
                            RepositoryId = 9,
                            Type = "Note",
                            UserId = "1"
                        },
                        new
                        {
                            AnnotationId = 11,
                            Content = "Sandbox looks promising for prototyping new ML models.",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5190),
                            RepositoryId = 10,
                            Type = "Note",
                            UserId = "2"
                        },
                        new
                        {
                            AnnotationId = 12,
                            Content = "Starter Kit",
                            CreatedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5190),
                            RepositoryId = 11,
                            Type = "Tag",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Backend"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Frontend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Artificial Intelligence"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Full Stack"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Data Science"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Security"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Testing"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Machine Learning"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RepositoryId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            CategoryId = 1,
                            Description = "A powerful backend framework for building scalable applications.",
                            Language = "C#",
                            RepositoryName = "Backend Framework",
                            RepositoryUrl = "https://github.com/example/backend-framework",
                            Stars = 1200
                        },
                        new
                        {
                            RepositoryId = 2,
                            CategoryId = 2,
                            Description = "A sleek and efficient frontend library.",
                            Language = "JavaScript",
                            RepositoryName = "Frontend Library",
                            RepositoryUrl = "https://github.com/example/frontend-library",
                            Stars = 950
                        },
                        new
                        {
                            RepositoryId = 3,
                            CategoryId = 3,
                            Description = "A comprehensive toolkit for AI research.",
                            Language = "Python",
                            RepositoryName = "AI Toolkit",
                            RepositoryUrl = "https://github.com/example/ai-toolkit",
                            Stars = 2500
                        },
                        new
                        {
                            RepositoryId = 4,
                            CategoryId = 5,
                            Description = "A hub of resources for data scientists.",
                            Language = "R",
                            RepositoryName = "Data Science Hub",
                            RepositoryUrl = "https://github.com/example/data-science-hub",
                            Stars = 1800
                        },
                        new
                        {
                            RepositoryId = 5,
                            CategoryId = 7,
                            Description = "An intuitive testing framework.",
                            Language = "Java",
                            RepositoryName = "Testing Framework",
                            RepositoryUrl = "https://github.com/example/testing-framework",
                            Stars = 700
                        },
                        new
                        {
                            RepositoryId = 8,
                            CategoryId = 6,
                            Description = "A comprehensive toolkit for cyber security.",
                            Language = "Python",
                            RepositoryName = "Cyber Security Toolkit",
                            RepositoryUrl = "https://github.com/example/security-toolkit",
                            Stars = 1300
                        },
                        new
                        {
                            RepositoryId = 9,
                            CategoryId = 7,
                            Description = "A robust framework for automated testing.",
                            Language = "Java",
                            RepositoryName = "Testing Framework Pro",
                            RepositoryUrl = "https://github.com/example/testing-framework-pro",
                            Stars = 1100
                        },
                        new
                        {
                            RepositoryId = 10,
                            CategoryId = 8,
                            Description = "An interactive sandbox for machine learning models.",
                            Language = "Python",
                            RepositoryName = "Machine Learning Sandbox",
                            RepositoryUrl = "https://github.com/example/ml-sandbox",
                            Stars = 2000
                        },
                        new
                        {
                            RepositoryId = 11,
                            CategoryId = 4,
                            Description = "A starter kit for full stack development projects.",
                            Language = "TypeScript",
                            RepositoryName = "Full Stack Starter Kit",
                            RepositoryUrl = "https://github.com/example/full-stack-starter",
                            Stars = 1500
                        },
                        new
                        {
                            RepositoryId = 12,
                            CategoryId = 5,
                            Description = "A library for creating stunning data visualizations.",
                            Language = "JavaScript",
                            RepositoryName = "Data Visualization Library",
                            RepositoryUrl = "https://github.com/example/data-visualization-lib",
                            Stars = 1400
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "021dcc24-74c5-43e8-930a-4d52faf4e895",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN_DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAENvc9w9jhVPLnTAWLw3l73o2JC8/OQgRDD/kgxyTVHwcvo5Aj1azn6OtoI2+pIcc/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5367b0db-b2f7-4ef4-aa8f-bd5f2e295511",
                            TwoFactorEnabled = false,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "45dfc125-583c-4ff8-85ec-931f7c55db44",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "JANE_SMITH",
                            PasswordHash = "AQAAAAIAAYagAAAAEBLDgbqoB2+6ZW4DfEqLPJzXRFmUFFFoWPokkaGqZzNzxGwFk3MpfcTh9M9D0xc2FQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cea86e96-0210-4a93-abea-8ed0de05cc41",
                            TwoFactorEnabled = false,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fabd3d51-cf76-4927-856b-c3d9da55fe31",
                            Email = "alice.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ALICE_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFp+7WzY2TkvzfN3mNLixwRT5mzfcm48NYyoiESmagPBav2PgLnmmPJ5r1yPr9kUuQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a24a3ae-e2c1-4e5d-99c0-6521ad16754a",
                            TwoFactorEnabled = false,
                            UserName = "alice_brown"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c13d0ff-531d-455d-adb2-19ef56adfcf6",
                            Email = "bob.jones@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Jones",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.JONES@EXAMPLE.COM",
                            NormalizedUserName = "BOB_JONES",
                            PasswordHash = "AQAAAAIAAYagAAAAECaghE+8EWAbz0fV3EYonJmtV6GVEO/XFUJRgh42dQc3Rcr2URn0aJKR4oAuK5jKgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be735619-5d9f-4d3b-8a41-c16118fa5fef",
                            TwoFactorEnabled = false,
                            UserName = "bob_jones"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "70b7e97b-6e5f-4a37-bea2-43c4f2fb91d3",
                            Email = "carla.white@example.com",
                            EmailConfirmed = true,
                            FirstName = "Carla",
                            LastName = "White",
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLA.WHITE@EXAMPLE.COM",
                            NormalizedUserName = "CARLA_WHITE",
                            PasswordHash = "AQAAAAIAAYagAAAAEMtK1OFV4MHDsbBTaDP7U0i/AznjLUt9e/Pfbo2FPcS3E984tY20I9dtK8ilOBwfvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8fe1ecba-8692-4357-8454-6edf4a2de57c",
                            TwoFactorEnabled = false,
                            UserName = "carla_white"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7357ee3a-5413-4745-a46f-3d781f870f86",
                            Email = "michael.green@example.com",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            LastName = "Green",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAEL.GREEN@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL_GREEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEOVvZXtyYmEc+wqjO0Pu2D1ODZKDMOCQY6uiwM7yJVQX0GgNKTEX9NtmNURHmwijQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2a366513-f120-4e03-90cf-a6c27c5060a3",
                            TwoFactorEnabled = false,
                            UserName = "michael_green"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "149528a1-6726-436e-a3ff-6e286f906d26",
                            Email = "linda.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.LEE@EXAMPLE.COM",
                            NormalizedUserName = "LINDA_LEE",
                            PasswordHash = "AQAAAAIAAYagAAAAEDDI1DgXe0x3ZAnDzkA7Vh56SpR/aakX4OGSiWq92ZnGhlcIWVUoJVuil8+GCcQKAQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8ab9a858-6b76-4e90-85f0-2c322cf8c129",
                            TwoFactorEnabled = false,
                            UserName = "linda_lee"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb7bec00-54b0-4043-a879-3323afb80b4d",
                            Email = "james.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "JAMES_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMXNodJwLiJ1wPnqRnK8jSDXJw63veOO90jiRu8d9SmM98HxNb1Ck0nwcWr6Nm7tsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6bb140a0-9d8f-49b2-8eda-50903917f035",
                            TwoFactorEnabled = false,
                            UserName = "james_brown"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a8d88979-57f5-48b3-b701-6c5e700fb45f",
                            Email = "emma.clark@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            LastName = "Clark",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.CLARK@EXAMPLE.COM",
                            NormalizedUserName = "EMMA_CLARK",
                            PasswordHash = "AQAAAAIAAYagAAAAEKdRNdvCR5hAW/QTld/O9qu8lVdRkyy9idWfRJHtvpCB+bvqQ0uY7ZoFW5vKY4+uvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1ec4b46-64d5-4c19-8def-f3d266ce7703",
                            TwoFactorEnabled = false,
                            UserName = "emma_clark"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "308299cb-d3a3-4fb4-9df5-2e7c28f46578",
                            Email = "daniel.evans@example.com",
                            EmailConfirmed = true,
                            FirstName = "Daniel",
                            LastName = "Evans",
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIEL.EVANS@EXAMPLE.COM",
                            NormalizedUserName = "DANIEL_EVANS",
                            PasswordHash = "AQAAAAIAAYagAAAAEFIz/PyyV3FufEPZIoFC8ZjiyE4jkxTBbJ72CECyJ327CNhFzKwe2XaYTAVVl/voAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a60b13b-70dc-4e2b-97d0-c246f72d55e4",
                            TwoFactorEnabled = false,
                            UserName = "daniel_evans"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("UserRepositories");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RepositoryId = 1,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(3930)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 2,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(3930)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 3,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(3940)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 4,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(3940)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(3940)
                        },
                        new
                        {
                            UserId = "6",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5080)
                        },
                        new
                        {
                            UserId = "7",
                            RepositoryId = 9,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "8",
                            RepositoryId = 10,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "9",
                            RepositoryId = 11,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "10",
                            RepositoryId = 12,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "1",
                            RepositoryId = 9,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 10,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5090)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 11,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5100)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 12,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5100)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 15, 21, 19, 6, 325, DateTimeKind.Utc).AddTicks(5100)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("Annotations")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("Annotations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Category", "Category")
                        .WithMany("Repositories")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
