// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSSFinalProject12_27.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NSSFinalProject12_27.Migrations
{
    [DbContext(typeof(NSSFinalProjectDbContext))]
    [Migration("20250102190321_UpdatedSeedData")]
    partial class UpdatedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnotationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnotationId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Annotations");

                    b.HasData(
                        new
                        {
                            AnnotationId = 1,
                            Content = "This backend framework looks promising for my next project.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8850),
                            RepositoryId = 1,
                            Type = "Note",
                            UserId = "1"
                        },
                        new
                        {
                            AnnotationId = 2,
                            Content = "Great library for frontend animations.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8850),
                            RepositoryId = 2,
                            Type = "Note",
                            UserId = "2"
                        },
                        new
                        {
                            AnnotationId = 3,
                            Content = "AI",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8850),
                            RepositoryId = 3,
                            Type = "Tag",
                            UserId = "3"
                        },
                        new
                        {
                            AnnotationId = 4,
                            Content = "Data science repo with useful algorithms.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8850),
                            RepositoryId = 4,
                            Type = "Note",
                            UserId = "4"
                        },
                        new
                        {
                            AnnotationId = 6,
                            Content = "Automated Testing",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8960),
                            RepositoryId = 9,
                            Type = "Tag",
                            UserId = "7"
                        },
                        new
                        {
                            AnnotationId = 7,
                            Content = "Great sandbox for testing ML algorithms.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8960),
                            RepositoryId = 10,
                            Type = "Note",
                            UserId = "8"
                        },
                        new
                        {
                            AnnotationId = 8,
                            Content = "Full Stack",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8960),
                            RepositoryId = 11,
                            Type = "Tag",
                            UserId = "9"
                        },
                        new
                        {
                            AnnotationId = 9,
                            Content = "Awesome data visualization library for presentations.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8960),
                            RepositoryId = 12,
                            Type = "Note",
                            UserId = "10"
                        },
                        new
                        {
                            AnnotationId = 10,
                            Content = "Could use this for testing in our current project.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8960),
                            RepositoryId = 9,
                            Type = "Note",
                            UserId = "1"
                        },
                        new
                        {
                            AnnotationId = 11,
                            Content = "Sandbox looks promising for prototyping new ML models.",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(9050),
                            RepositoryId = 10,
                            Type = "Note",
                            UserId = "2"
                        },
                        new
                        {
                            AnnotationId = 12,
                            Content = "Starter Kit",
                            CreatedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(9050),
                            RepositoryId = 11,
                            Type = "Tag",
                            UserId = "3"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Backend"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Frontend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Artificial Intelligence"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Full Stack"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Data Science"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Security"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Testing"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Machine Learning"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RepositoryId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            CategoryId = 1,
                            Description = "A powerful backend framework for building scalable applications.",
                            Language = "C#",
                            RepositoryName = "Backend Framework",
                            RepositoryUrl = "https://github.com/example/backend-framework",
                            Stars = 1200
                        },
                        new
                        {
                            RepositoryId = 2,
                            CategoryId = 2,
                            Description = "A sleek and efficient frontend library.",
                            Language = "JavaScript",
                            RepositoryName = "Frontend Library",
                            RepositoryUrl = "https://github.com/example/frontend-library",
                            Stars = 950
                        },
                        new
                        {
                            RepositoryId = 3,
                            CategoryId = 3,
                            Description = "A comprehensive toolkit for AI research.",
                            Language = "Python",
                            RepositoryName = "AI Toolkit",
                            RepositoryUrl = "https://github.com/example/ai-toolkit",
                            Stars = 2500
                        },
                        new
                        {
                            RepositoryId = 4,
                            CategoryId = 5,
                            Description = "A hub of resources for data scientists.",
                            Language = "R",
                            RepositoryName = "Data Science Hub",
                            RepositoryUrl = "https://github.com/example/data-science-hub",
                            Stars = 1800
                        },
                        new
                        {
                            RepositoryId = 5,
                            CategoryId = 7,
                            Description = "An intuitive testing framework.",
                            Language = "Java",
                            RepositoryName = "Testing Framework",
                            RepositoryUrl = "https://github.com/example/testing-framework",
                            Stars = 700
                        },
                        new
                        {
                            RepositoryId = 8,
                            CategoryId = 6,
                            Description = "A comprehensive toolkit for cyber security.",
                            Language = "Python",
                            RepositoryName = "Cyber Security Toolkit",
                            RepositoryUrl = "https://github.com/example/security-toolkit",
                            Stars = 1300
                        },
                        new
                        {
                            RepositoryId = 9,
                            CategoryId = 7,
                            Description = "A robust framework for automated testing.",
                            Language = "Java",
                            RepositoryName = "Testing Framework Pro",
                            RepositoryUrl = "https://github.com/example/testing-framework-pro",
                            Stars = 1100
                        },
                        new
                        {
                            RepositoryId = 10,
                            CategoryId = 8,
                            Description = "An interactive sandbox for machine learning models.",
                            Language = "Python",
                            RepositoryName = "Machine Learning Sandbox",
                            RepositoryUrl = "https://github.com/example/ml-sandbox",
                            Stars = 2000
                        },
                        new
                        {
                            RepositoryId = 11,
                            CategoryId = 4,
                            Description = "A starter kit for full stack development projects.",
                            Language = "TypeScript",
                            RepositoryName = "Full Stack Starter Kit",
                            RepositoryUrl = "https://github.com/example/full-stack-starter",
                            Stars = 1500
                        },
                        new
                        {
                            RepositoryId = 12,
                            CategoryId = 5,
                            Description = "A library for creating stunning data visualizations.",
                            Language = "JavaScript",
                            RepositoryName = "Data Visualization Library",
                            RepositoryUrl = "https://github.com/example/data-visualization-lib",
                            Stars = 1400
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a5fc721e-6d98-4679-b011-d05c6364b5ae",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN_DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEOq55BAWd29L6udyEeg/20jkOKxgH4AmbixfO214Ec1edRPG//c9wpwrO7FJy3li7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c8244756-899f-4be7-a64b-4f771a0757cd",
                            TwoFactorEnabled = false,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce8736fa-5959-425c-938a-81811fb26a8f",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "JANE_SMITH",
                            PasswordHash = "AQAAAAIAAYagAAAAECke8KDqf7w1XiFypLtdD/wQ7/xSAtV+0kPmvhbCdT07hcv/BPW+iiZZ7dZ09k3kyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e5ede00-393b-4bb1-ae41-d8b03f262b73",
                            TwoFactorEnabled = false,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b311fa28-8f22-495c-a702-be49005fc4c0",
                            Email = "alice.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ALICE_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAENXHE7t3Wy+ycGyYN7seKv9Thn69Cbbv0MxyWezc58A9okQ9EP/MHwruwG2GesZ9Tg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d6bcf5bf-7599-4412-a414-3c51289db3a8",
                            TwoFactorEnabled = false,
                            UserName = "alice_brown"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14120af4-8300-4b8f-aad1-5f49c1edeee0",
                            Email = "bob.jones@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Jones",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.JONES@EXAMPLE.COM",
                            NormalizedUserName = "BOB_JONES",
                            PasswordHash = "AQAAAAIAAYagAAAAEDGiApN5Qvme5DY741ko9PwPmg/FSAbVTYkOP42lphIdTTuk+tKG+j3+2rnfWDI2BQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f44068e7-eece-4a8b-be34-a4d9613e1917",
                            TwoFactorEnabled = false,
                            UserName = "bob_jones"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f759c03e-083a-42df-b141-a32a381f5ba4",
                            Email = "carla.white@example.com",
                            EmailConfirmed = true,
                            FirstName = "Carla",
                            LastName = "White",
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLA.WHITE@EXAMPLE.COM",
                            NormalizedUserName = "CARLA_WHITE",
                            PasswordHash = "AQAAAAIAAYagAAAAEETrIBqtS9yv/bwtAjmWKD8bN9yBCFioWm7twVFy+K/FHQHeplCdxj0oK4xDGIMIKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8f9a9d39-913d-46f2-9b38-6f05dc6327ea",
                            TwoFactorEnabled = false,
                            UserName = "carla_white"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47dd0255-3539-461c-8d72-63cb1b7a26c5",
                            Email = "michael.green@example.com",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            LastName = "Green",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAEL.GREEN@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL_GREEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPZ5UFjvhtegJh71JUQi3x+GTowgD878Y9CxQ1lmZ5u/STjwrZkzUfijlD1EEBw6iQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bd37b527-74b7-431f-a490-7b197fb24bda",
                            TwoFactorEnabled = false,
                            UserName = "michael_green"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83d3b62e-b985-40cf-8a26-8130c64e6ade",
                            Email = "linda.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.LEE@EXAMPLE.COM",
                            NormalizedUserName = "LINDA_LEE",
                            PasswordHash = "AQAAAAIAAYagAAAAED7orH4j9TNVPh74MSLYXEGZ4Avj3l0V3kO/AVkeK0I1VI0FR72cULPFg22jdndmxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c86630ab-6d83-4aea-ae36-3c4b2e934ba2",
                            TwoFactorEnabled = false,
                            UserName = "linda_lee"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2007e017-6a8d-4a27-9c10-6d066f7b27c9",
                            Email = "james.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "JAMES_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPANjshPm1BsAfQpSKGKCEIqxzkyfR6E9TdGPNc9R2QNanyuair61/6d6cHZkQkJbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "79bc71f4-0874-4191-a466-8775f60d0e56",
                            TwoFactorEnabled = false,
                            UserName = "james_brown"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "487e2dbc-008e-4be9-8611-349536650554",
                            Email = "emma.clark@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            LastName = "Clark",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.CLARK@EXAMPLE.COM",
                            NormalizedUserName = "EMMA_CLARK",
                            PasswordHash = "AQAAAAIAAYagAAAAEHq3KSeYC08Lzq3ZLOh8ipTraMajlRQ+rNsn/jV0UUZ6Q+CKheoN5ovWqz10eq0zjA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "246ae30b-6040-4372-bf4d-93e6d470b851",
                            TwoFactorEnabled = false,
                            UserName = "emma_clark"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "76a296eb-7b46-49d7-a383-92d792a8f7a3",
                            Email = "daniel.evans@example.com",
                            EmailConfirmed = true,
                            FirstName = "Daniel",
                            LastName = "Evans",
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIEL.EVANS@EXAMPLE.COM",
                            NormalizedUserName = "DANIEL_EVANS",
                            PasswordHash = "AQAAAAIAAYagAAAAEOkRN/ZoFG6qmtkO+KHeWKBLzuT8nfoxORuvK/l43RkODY/0p3h4jO/j0zpzWczjOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "088b4514-aa48-4f87-92c3-8a0758e5599f",
                            TwoFactorEnabled = false,
                            UserName = "daniel_evans"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("UserRepositories");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RepositoryId = 1,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8800)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 2,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8810)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 3,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8810)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 4,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8810)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8810)
                        },
                        new
                        {
                            UserId = "6",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "7",
                            RepositoryId = 9,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "8",
                            RepositoryId = 10,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "9",
                            RepositoryId = 11,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "10",
                            RepositoryId = 12,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "1",
                            RepositoryId = 9,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 10,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 11,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8920)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 12,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8930)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 2, 19, 3, 20, 808, DateTimeKind.Utc).AddTicks(8930)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("Annotations")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("Annotations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Category", "Category")
                        .WithMany("Repositories")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
