// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NSSFinalProject12_27.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NSSFinalProject12_27.Migrations
{
    [DbContext(typeof(NSSFinalProjectDbContext))]
    partial class NSSFinalProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnotationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnotationId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Annotations");

                    b.HasData(
                        new
                        {
                            AnnotationId = 1,
                            Content = "This backend framework looks promising for my next project.",
                            CreatedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2280),
                            RepositoryId = 1,
                            Type = "Note",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Backend"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Frontend"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Artificial Intelligence"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Full Stack"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Data Science"
                        },
                        new
                        {
                            CategoryId = 6,
                            Description = "Security"
                        },
                        new
                        {
                            CategoryId = 7,
                            Description = "Testing"
                        },
                        new
                        {
                            CategoryId = 8,
                            Description = "Machine Learning"
                        },
                        new
                        {
                            CategoryId = 9,
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RepositoryId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer");

                    b.HasKey("RepositoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            CategoryId = 1,
                            CreatorUserId = "1",
                            Description = "A powerful backend framework for building scalable applications.",
                            Language = "C#",
                            RepositoryName = "Backend Framework",
                            RepositoryUrl = "https://github.com/example/backend-framework",
                            Stars = 1200
                        },
                        new
                        {
                            RepositoryId = 2,
                            CategoryId = 2,
                            CreatorUserId = "2",
                            Description = "A sleek and efficient frontend library.",
                            Language = "JavaScript",
                            RepositoryName = "Frontend Library",
                            RepositoryUrl = "https://github.com/example/frontend-library",
                            Stars = 950
                        },
                        new
                        {
                            RepositoryId = 3,
                            CategoryId = 3,
                            CreatorUserId = "3",
                            Description = "A comprehensive toolkit for AI research.",
                            Language = "Python",
                            RepositoryName = "AI Toolkit",
                            RepositoryUrl = "https://github.com/example/ai-toolkit",
                            Stars = 2500
                        },
                        new
                        {
                            RepositoryId = 4,
                            CategoryId = 5,
                            CreatorUserId = "4",
                            Description = "A hub of resources for data scientists.",
                            Language = "R",
                            RepositoryName = "Data Science Hub",
                            RepositoryUrl = "https://github.com/example/data-science-hub",
                            Stars = 1800
                        },
                        new
                        {
                            RepositoryId = 5,
                            CategoryId = 7,
                            CreatorUserId = "5",
                            Description = "An intuitive testing framework.",
                            Language = "Java",
                            RepositoryName = "Testing Framework",
                            RepositoryUrl = "https://github.com/example/testing-framework",
                            Stars = 700
                        },
                        new
                        {
                            RepositoryId = 6,
                            CategoryId = 6,
                            CreatorUserId = "6",
                            Description = "A comprehensive toolkit for cyber security.",
                            Language = "Python",
                            RepositoryName = "Cyber Security Toolkit",
                            RepositoryUrl = "https://github.com/example/security-toolkit",
                            Stars = 1300
                        },
                        new
                        {
                            RepositoryId = 7,
                            CategoryId = 6,
                            CreatorUserId = "7",
                            Description = "An AI-driven system to detect and prevent security threats.",
                            Language = "Python",
                            RepositoryName = "AI-Powered Threat Detection",
                            RepositoryUrl = "https://github.com/example/ai-threat-detection",
                            Stars = 1700
                        },
                        new
                        {
                            RepositoryId = 8,
                            CategoryId = 6,
                            CreatorUserId = "8",
                            Description = "A suite of tools to secure cloud environments efficiently.",
                            Language = "Go",
                            RepositoryName = "Cloud Security Suite",
                            RepositoryUrl = "https://github.com/example/cloud-security-suite",
                            Stars = 1900
                        },
                        new
                        {
                            RepositoryId = 9,
                            CategoryId = 2,
                            CreatorUserId = "9",
                            Description = "A powerful web scraping tool with automation features.",
                            Language = "JavaScript",
                            RepositoryName = "Web Scraper Pro",
                            RepositoryUrl = "https://github.com/example/web-scraper-pro",
                            Stars = 1500
                        },
                        new
                        {
                            RepositoryId = 10,
                            CategoryId = 8,
                            CreatorUserId = "10",
                            Description = "An interactive sandbox for machine learning models.",
                            Language = "Python",
                            RepositoryName = "Machine Learning Sandbox",
                            RepositoryUrl = "https://github.com/example/ml-sandbox",
                            Stars = 2000
                        },
                        new
                        {
                            RepositoryId = 11,
                            CategoryId = 4,
                            CreatorUserId = "2",
                            Description = "A starter kit for full stack development projects.",
                            Language = "TypeScript",
                            RepositoryName = "Full Stack Starter Kit",
                            RepositoryUrl = "https://github.com/example/full-stack-starter",
                            Stars = 1500
                        },
                        new
                        {
                            RepositoryId = 12,
                            CategoryId = 5,
                            CreatorUserId = "4",
                            Description = "A library for creating stunning data visualizations.",
                            Language = "JavaScript",
                            RepositoryName = "Data Visualization Library",
                            RepositoryUrl = "https://github.com/example/data-visualization-lib",
                            Stars = 1400
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ea1fa0a-7735-4905-b9e4-5347ff3b30a5",
                            Email = "john.doe@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHN.DOE@EXAMPLE.COM",
                            NormalizedUserName = "JOHN_DOE",
                            PasswordHash = "AQAAAAIAAYagAAAAEItgi/ITIGUs2bhF64whahwE3F2sR9lqES//S5CzSaTP/sIjvag2ZMLWXAMLGE678g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33a9185e-e68c-4ba0-a49a-928984d12845",
                            TwoFactorEnabled = false,
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "910c55af-1d0b-4e36-bde6-a78ee3731bae",
                            Email = "jane.smith@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "JANE_SMITH",
                            PasswordHash = "AQAAAAIAAYagAAAAELfcGDHGcayGVEUYebxcQ2fyeTfqZiMPk1EE9BNb0zmk7l05ST2hmjCLlVgUxv4UhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1ffeec9-99b0-4a6c-8ef1-878229a8243f",
                            TwoFactorEnabled = false,
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52073590-7624-4415-a871-cb48763dd6fc",
                            Email = "alice.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "Alice",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "ALICE_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGVgnBS9pc4WZaKm4jcky/2SVQ+T8VwKL6XiU02w0qGe2MNTwclMQ0AakOB10pXECg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eca6ae94-e3f4-4157-84c2-cf59319c5a5f",
                            TwoFactorEnabled = false,
                            UserName = "alice_brown"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "32266dd8-8c1e-4a3a-9546-d34d64cebf60",
                            Email = "bob.jones@example.com",
                            EmailConfirmed = true,
                            FirstName = "Bob",
                            LastName = "Jones",
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.JONES@EXAMPLE.COM",
                            NormalizedUserName = "BOB_JONES",
                            PasswordHash = "AQAAAAIAAYagAAAAEKmuDXut8/c4yBhbVz9jlzGfRRxO0T6OhgeKyBKrjZ8AuA8i1JLbNhlBhUZSDbJ/2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8dc12854-430c-48e1-aefb-ce5eca2f24b9",
                            TwoFactorEnabled = false,
                            UserName = "bob_jones"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ec71c303-0e3e-4960-a35e-72030a2c16d6",
                            Email = "carla.white@example.com",
                            EmailConfirmed = true,
                            FirstName = "Carla",
                            LastName = "White",
                            LockoutEnabled = false,
                            NormalizedEmail = "CARLA.WHITE@EXAMPLE.COM",
                            NormalizedUserName = "CARLA_WHITE",
                            PasswordHash = "AQAAAAIAAYagAAAAEM55Wqv8abQ2Ubr+JVS7+DvKehIfvKr4j1BEhpgSxz4v9FmWfiMnPhO5euiQdnzXkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3deba606-d0d5-4dc0-a7bc-d153fa5302b7",
                            TwoFactorEnabled = false,
                            UserName = "carla_white"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00420993-218a-49c5-8d6f-66b35269ab52",
                            Email = "michael.green@example.com",
                            EmailConfirmed = true,
                            FirstName = "Michael",
                            LastName = "Green",
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAEL.GREEN@EXAMPLE.COM",
                            NormalizedUserName = "MICHAEL_GREEN",
                            PasswordHash = "AQAAAAIAAYagAAAAELy9+zJrEo7frWeJBP+eN6uqJK4iB20tdGMFIhqvUN14ATA+WrQamS+ylFRBLWz+Ug==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "43b48886-36d6-434e-959b-12a2c2f42d86",
                            TwoFactorEnabled = false,
                            UserName = "michael_green"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b9c6b839-5e2c-4d7e-819e-d9dbf5590833",
                            Email = "linda.lee@example.com",
                            EmailConfirmed = true,
                            FirstName = "Linda",
                            LastName = "Lee",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDA.LEE@EXAMPLE.COM",
                            NormalizedUserName = "LINDA_LEE",
                            PasswordHash = "AQAAAAIAAYagAAAAEPwHluT/Pes4reL5H57xvlfzlJ347g5dXvjKarQEGTZwjQpOPS8qoXIZM5GabEbMWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "18733c7d-fb99-4260-8692-cde07b45d6f3",
                            TwoFactorEnabled = false,
                            UserName = "linda_lee"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c1a9d94-434a-478b-a7cd-7a2e0cc73b8c",
                            Email = "james.brown@example.com",
                            EmailConfirmed = true,
                            FirstName = "James",
                            LastName = "Brown",
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMES.BROWN@EXAMPLE.COM",
                            NormalizedUserName = "JAMES_BROWN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDqkt9xH7zuwlircvhUZuysU3cxLYlzy+QSsO2umENlkfPVJw16gYiv4/kA10yVydQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d02cec7e-f62a-4f58-b239-65f1b4ab730c",
                            TwoFactorEnabled = false,
                            UserName = "james_brown"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "917d0172-3448-4087-a059-9d914769297b",
                            Email = "emma.clark@example.com",
                            EmailConfirmed = true,
                            FirstName = "Emma",
                            LastName = "Clark",
                            LockoutEnabled = false,
                            NormalizedEmail = "EMMA.CLARK@EXAMPLE.COM",
                            NormalizedUserName = "EMMA_CLARK",
                            PasswordHash = "AQAAAAIAAYagAAAAEM28kcAw0VmofuUDXnzx83INrnZf7NW30scOCHEB102Kekk6x0WE1aSf7CyKPXv/RA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a942c843-a274-47e3-a01f-b8a809a656d2",
                            TwoFactorEnabled = false,
                            UserName = "emma_clark"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f199a769-314d-4e06-9060-dfe606aaadcb",
                            Email = "daniel.evans@example.com",
                            EmailConfirmed = true,
                            FirstName = "Daniel",
                            LastName = "Evans",
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIEL.EVANS@EXAMPLE.COM",
                            NormalizedUserName = "DANIEL_EVANS",
                            PasswordHash = "AQAAAAIAAYagAAAAEJt2Hv/Zlf2heSOOAf5/pI8w7GkVnDhiTqoukjD3cuMLFxjurE2BGGLFG00L9rpPDQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "018d47ee-f929-4fca-a82f-66e046077d81",
                            TwoFactorEnabled = false,
                            UserName = "daniel_evans"
                        });
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("UserRepositories");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RepositoryId = 1,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2190)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 2,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 3,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 4,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "6",
                            RepositoryId = 6,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "7",
                            RepositoryId = 7,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "8",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "9",
                            RepositoryId = 9,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "10",
                            RepositoryId = 10,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2200)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 11,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 12,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "6",
                            RepositoryId = 3,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "8",
                            RepositoryId = 3,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "1",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "9",
                            RepositoryId = 5,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "2",
                            RepositoryId = 6,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "5",
                            RepositoryId = 6,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "4",
                            RepositoryId = 7,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "9",
                            RepositoryId = 7,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2210)
                        },
                        new
                        {
                            UserId = "10",
                            RepositoryId = 7,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2220)
                        },
                        new
                        {
                            UserId = "3",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2220)
                        },
                        new
                        {
                            UserId = "6",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2220)
                        },
                        new
                        {
                            UserId = "7",
                            RepositoryId = 8,
                            SavedAt = new DateTime(2025, 1, 23, 18, 2, 38, 700, DateTimeKind.Utc).AddTicks(2220)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NSSFinalProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NSSFinalProject.Models.Annotation", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("Annotations")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("Annotations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Category", "Category")
                        .WithMany("Repositories")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NSSFinalProject.Models.UserRepository", b =>
                {
                    b.HasOne("NSSFinalProject.Models.Repository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NSSFinalProject.Models.User", "User")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Category", b =>
                {
                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.Repository", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("NSSFinalProject.Models.User", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("UserRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
